### get all persons
GET https://backend-dome.herokuapp.com/persons

### get person
GET https://backend-dome.herokuapp.com/persons/3

### get not exist person
GET https://backend-dome.herokuapp.com/persons/10

### add error person info
POST https://backend-dome.herokuapp.com/persons
Content-Type: application/json

{
    "name": "",
    "number": 198231413132
}

### add error person info
POST https://backend-dome.herokuapp.com/persons
Content-Type: application/json

{
    "name": "jack",
    "number": ""
}

### add person
POST https://backend-dome.herokuapp.com/persons
Content-Type: application/json

{
    "name": "ray",
    "number": 198231413132
}

### change person info
# PUT https://backend-dome.herokuapp.com/persons HTTP/1.1
# Content-Type: application/json

# {
#     "name": "tom",
#     "number": 123456789
# }

### delete person
DELETE https://backend-dome.herokuapp.com/persons/1 HTTP/1.1

### delete not exist person
DELETE https://backend-dome.herokuapp.com/persons/10 HTTP/1.1